title: 新全球经济的诞生
description: 如果过去40年经济历史中定义规则的是一次性的、具有历史偶然性的现象，而这些规则现在正迅速走向终结，会怎样？
theme: jekyll-theme-slate
markdown: kramdown
url: "https://juliocedillo.github.io/"
baseurl: "neweconomy-zh"
logo: "https://juliocedillo.github.io/assets/images/seal.ico"
